<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Lokesh" name="takescreenshot.DemoListener" tests="3" failures="1" timestamp="15 Sep 2023 04:11:11 GMT" time="75.502" errors="0">
  <testcase name="clickOnAdvanceJavaLink" time="18.621" classname="takescreenshot.DemoListener"/>
  <testcase name="testToFail" time="32.819" classname="takescreenshot.DemoListener">
    <failure type="java.lang.AssertionError" message="expected [Nike - Shop for Nike Apparels Online in India | Myntra] but found [Niki - Shop for Nike Apparels Online in India | Myntra]">
      <![CDATA[java.lang.AssertionError: expected [Nike - Shop for Nike Apparels Online in India | Myntra] but found [Niki - Shop for Nike Apparels Online in India | Myntra]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at takescreenshot.DemoListener.testToFail(DemoListener.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testToFail -->
  <testcase name="OpenSite" time="24.062" classname="takescreenshot.DemoListener"/>
</testsuite> <!-- takescreenshot.DemoListener -->
